name: Auto Zip wp-content and Add to Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # needed to upload release assets

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the code from the release commit
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Create current release file for auto-patch system
      - name: Create current release file
        run: |
          RELEASE_TAG="${GITHUB_REF_NAME}"
          echo "<?php define('CURRENT_RELEASE', '${RELEASE_TAG}'); ?>" > wp-content/current_release.php
          echo "Created release file with tag: ${RELEASE_TAG}"

      # 3️⃣ Zip the wp-content folder
      - name: Create wp-content.zip
        run: |
          if [ -d "wp-content" ]; then
            zip -r wp-content.zip wp-content
          else
            echo "wp-content directory not found!" && exit 1
          fi

      # 3️⃣ Upload the zip file to the GitHub release
      - name: Upload wp-content.zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: wp-content.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
